version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    package-ecosystem: cargo
    directory: "/app/rs"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
